<?php
$headTitle = 'Add Upload';
$this->headtitle($headTitle);
?>
<h3><?= $this->escapeHtml($headTitle) ?></h3>
<br>
<?php if ($this->error) : ?>
<p class="font-color-red">
    There were one or more issue with your submission.<br>
    Please, correct them as indicated below.
</p>
<br>
<?php endif; ?>
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10 col-xs-8">
        <?php
        $form->setAttribute('action', $this->url('user/upload', array(
            'action' => 'add',          
        )));
        
        $form->prepare();
        
        echo $this->form()->openTag($form);      
        ?>
        <div class="form-group">
            <div class="col-sm-3">
                <?= $this->formLabel($form->get('label')) ?>
            </div>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('label')) ?>
                <?= $this->formElementErrors($form->get('label')) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-3">
                <?= $this->formLabel($form->get('filename')) ?>
            </div>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('filename')) ?>
                <?= $this->formElementErrors($form->get('filename')) ?>
                <?php if ($message) : ?>
                    <ul>
                       <li>
                           File with name "<strong><?= $this->escapeHtml($message) ?></strong>" exists already.<br>
                           Please change the file name.
                       </li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
        <div class="form-group">           
            <div class="col-sm-12 col-sm-offset-3">
                <?= $this->formElement($form->get('submit')) ?>               
            </div>
        </div>
        
        
        <?= $this->form()->closeTag() ?>
    </div>
</div>
