<?php
$headTitle = 'Group Chat';
$this->headTitle($headTitle);
?>
<?php 
echo $this->headStyle('
         .chat-container{ width: 80%; }
         #chatList { width: 100%; border: 1px solid #ccc; border-radius: 5px; height: 400px; }
         #chatForm { width: 100%; }
     ');
?>
<h3><?= $this->escapeHtml($headTitle) ?></h3>
<br>
<section class="chat-container">
    <iframe src="<?= $this->url('user/chat', array('action' => 'messagesList')) ?>" id="chatList"></iframe>
    <br>
    <br>
    <?php 
    $form->setAttribute('action', $this->url('user/chat', array(
        'action' => 'addMessage',
    )));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    ?>
    <div class="form-group">
        <?= $this->formLabel($form->get('message')) ?>
        <div>
            <?= $this->formElement($form->get('message')) ?>
            <?= $this->formElementErrors($form->get('message')) ?>
        </div>
    </div>
    <div class="form-group">
        <?= $this->formElement($form->get('submit')) ?>                   
    </div>
    <?= $this->form()->closeTag() ?>
</section>
