<?php
$headTitle = 'Main Page';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-xs-6">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
    <div class="col-xs-6">
        <ul class="list-inline pull-right login-register-block">
            <?php if ($email) : ?>
                <li>Welcome: <strong><?= $this->escapeHtml($email) ?></strong></li> |
                <li><a href="/user/login/logout"><i class="fa fa-sign-out"></i> Logout</a></li>
            <?php else : ?>
                <li><a href="/user/login"><i class="fa fa-sign-in"></i> Login</a></li> |
                <li><a href="/user/register"><i class="fa fa-registered"></i> Register</a></li>
            <?php endif; ?>
        </ul>
    </div>
</div>
